version: '3'
services:
      webservice_name:
            container_name: website
            build:
                  context: .
                  dockerfile: Dockerfile
            restart: unless-stopped
            depends_on:
                  - parrainagedb
            networks:
                  expose-network:
                  pgsql-network:
            volumes:
                  - /PATH/TO/VOLUME:/var/www/html
            labels:
                  #Redirect to https (don t include in other services)
                  - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
                  - "traefik.enable=true"
                  # Set host
                  - "traefik.http.routers.mibdeparrain.rule=Host(`your.url.url`)"
                  # Set service
                  - "traefik.http.services.mibdeparrain.loadbalancer.server.port=80"
                  - "traefik.http.routers.mibdeparrain.tls.certresolver=le"
                  # Set to the secure endpoint
                  - "traefik.http.routers.mibdeparrain.entrypoints=secure"
                  # Redirect
                  - "traefik.http.routers.mibdeparrain-redir.rule=Host(`your.url.url`)"
                  - "traefik.http.routers.mibdeparrain-redir.entrypoints=insecure"
                  - "traefik.http.routers.mibdeparrain-redir.middlewares=redirect-to-https"
      databaseservice_name:
            container_name: pgsql_server
            image: postgres:latest
            networks:
                  pgsql-network:
            volumes:
                  - /PATH/TO/VOLUME:/var/lib/pgsql
            restart: always
            environment:
                  POSTGRES_DB: database.name
                  POSTGRES_USER: user.name
                  POSTGRES_PASSWORD: user.password
            ports:
                  - '3306:3306'
networks:
  expose-network:
    external:
      name: expose-network
  pgsql-network:
    driver: bridge
