version: '3'
services:
      webservice_name:
            container_name: website.container.name
            build:
                  context: .
                  dockerfile: Dockerfile
            restart: unless-stopped
            depends_on:
                  - databaseservice_name
            networks:
                  expose-network:
                  mysql-network:
            volumes:
                  - path.to.website:/var/www/html
            labels:
                  #Redirect to https (don t include in other services)
                  - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
                  - "traefik.enable=true"
                  # Set host
                  - "traefik.http.routers.webservice_name.rule=Host(`your.url.url`)"
                  # Set service
                  - "traefik.http.services.webservice_name.loadbalancer.server.port=80"
                  - "traefik.http.routers.webservice_name.tls.certresolver=le"
                  # Set to the secure endpoint
                  - "traefik.http.routers.webservice_name.entrypoints=secure"
                  # Redirect
                  - "traefik.http.routers.webservice_name-redir.rule=Host(`your.url.url`)"
                  - "traefik.http.routers.webservice_name-redir.entrypoints=insecure"
                  - "traefik.http.routers.webservice_name-redir.middlewares=redirect-to-https"
      databaseservice_name:
            container_name: database_server.container.name
            image: mysql:latest
            networks:
                  mysql-network:
            command: --default-authentication-plugin=mysql_native_password
            volumes:
                  - path.to.db:/var/lib/mysql
            restart: always
            environment:
                  MYSQL_ROOT_PASSWORD: root.password
                  MYSQL_DATABASE: database.name
                  MYSQL_USER: user.name
                  MYSQL_PASSWORD: user.password
            ports:
                  - '3306:3306'
networks:
  expose-network:
    external:
      name: expose-network
  mysql-network:
    driver: bridge
